imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
 filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
braincrafted_bootstrap:
    less_filter: less
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     8000
        dbname:   symfony
        user:     root
        password: null
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#Gregwar captcha nastavitve
gregwar_captcha: ~


#Nastavitve za f0s bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jan\ProjektBundle\Entity\User


#Nastavitve za upload bundle
vich_uploader:
    db_driver: orm

    mappings:                 
      imageName:                                                          #Mora se ujemati z entiteto
        uri_prefix: /datoteke/cv                                          #Lokacija
        upload_destination: %kernel.root_dir%/../web/datoteke/cv          #Lokacija

        inject_on_load:    true                                           #
        delete_on_update:    true                                         #Ce se spremeni, ko spremenimo vpis
        delete_on_remove:    true                                         #Ce se zbrise, ko zbrisemo vpis

