pokazi{jan_projekt_delovnomesto:
    resource: "@JanProjektBundle/Resources/config/routing/delovnomesto.yml"
    prefix:   /delovnomesto

jan_projekt_prijava:
    resource: "@JanProjektBundle/Resources/config/routing/prijava.yml"
    prefix:   /prijava

jan_projekt_zaposlovalec:
    resource: "@JanProjektBundle/Resources/config/routing/zaposlovalec.yml"
    prefix:   /zaposlovalec

jan_projekt_pokazi_seznam_delovnih_mest:
    pattern: /seznam_delovnih_mest/
    defaults: {_controller: JanProjektBundle:Default:pokazi_seznam}

jan_projekt_pokazi_delovno_mesto:
    pattern: delovno_mesto/{id}
    defaults: {_controller: JanProjektBundle:Default:pokazi}
    requirements:
      id: \d+

jan_projekt_dodaj:
    pattern: /delovno_mesto/dodaj_delovno_mesto
    defaults: {_controller: JanProjektBundle:Default:dodaj}


jan_projekt_pokazi_seznam_prijav:
    pattern: /seznam_prijav/
    defaults: {_controller: JanProjektBundle:Default:pokazi_seznam_prijav}

jan_projekt_pokazi_prijavo:
    pattern: prijava/{id}
    defaults: {_controller: JanProjektBundle:Default:pokazi_prijavo}
    requirements:
      id: \d+

jan_projekt_dodaj_prijavo:
    pattern: /prijava/dodaj_prijavo
    defaults: {_controller: JanProjektBundle:Default:dodaj_prijavo}


jan_projekt_dodaj_prva:
    pattern: /prva
    defaults: {_controller: JanProjektBundle:Default:prva}

jan_projekt_success:
    pattern: /uspesno
    defaults: {_controller: JanProjektBundle:Default:success}
