services:
#    jan_projekt.example:
#        class: Jan\ProjektBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    jan_security.component.authentication.handler.login_success_handler.class: Jan\ProjektBundle\Component\Authentication\Handler\LoginFailureHandler
    jan_security.component.authentication.handler.logout_success_handler.class: Jan\ProjektBundle\Component\Authentication\Handler\LogoutSuccessHandler
    
services:
    jan_security.component.authentication.handler.login_success_handler:
        class:  %jan_security.component.authentication.handler.login_success_handler.class%
        arguments:  [@service_container, @router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
    jan_security.component.authentication.handler.logout_success_handler:
        class:  %jan_security.component.authentication.handler.logout_success_handler.class%
        arguments:  [@service_container, @router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
